create table if not exists public.swim_log (
  id bigint generated by default as identity primary key,
  date date not null,
  distance_miles numeric(10, 5) not null check (distance_miles > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  start_date date not null,
  target_miles numeric(10, 2) not null default 22,
  target_money numeric(10, 2) not null default 220,
  justgiving_page_slug text not null
);

alter table public.swim_log enable row level security;
alter table public.settings enable row level security;

create policy "Public can read swim_log"
on public.swim_log
for select
to anon
using (true);

create policy "Public can insert swim_log"
on public.swim_log
for insert
to anon
with check (distance_miles > 0);

create policy "Public can read settings"
on public.settings
for select
to anon
using (true);
